// Generated by CoffeeScript 1.8.0
console.log("Initializing AngularJS");

window.app = angular.module('app', ['ngRoute']);

window.app.config([
  '$routeProvider', function($routeProvider) {
    $routeProvider.when('/page1', {
      templateUrl: 'partials/page1.html',
      controller: 'pageOneController'
    }).when('/page2', {
      templateUrl: 'partials/page2.html',
      controller: 'pageTwoController'
    }).otherwise({
      redirectTo: '/page1'
    });
  }
]);

window.app.controller('pageOneController', [
  '$scope', function($scope) {
    console.log("Page 1");
  }
]);

window.app.controller('pageTwoController', [
  '$scope', function($scope) {
    console.log("Page 2");
  }
]);
